# -*- coding: utf-8 -*-
"""Aula8-Análise_Exploratória.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17VRoN4i32FPEkrlopCyKV317uZ0c3LsT
"""

#Impotando as Bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('seaborn')

#Upload do arquivo
from google.colab import files
arq = files.upload()

#Criando nosso DataFrame
df = pd.read_excel('vendas-representante-vendedor.xlsx')

#Visualizando as 5 primeiras linhas
df.head(10)

#Consulta de linhas faltantes:

df.isnull().sum()

#Quantidade de linhas e colunas
df.shape

df.dtypes

df.sample(10)

#Qual a rceita total?

df['Faturamento'].sum()

#Qual o custo total?
 df['Custo'] = df['Faturamento'].mul(df['Qtde de Vendas']) #Criando a coluna custo

df.head(1)

#Qual o custo total
round(df['Custo'].sum(), 2)

#Agora que temos a receita, custo e o total, podemos achar o lucro total
#Vamos criar uma coluna de lucro que será Receita - Custo

df['Lucro'] =  df['Custo'] - df['Faturamento']

df.head(5)

#Total Lucro
round(df['Lucro'].sum(), 2)

#Qual o total de produtos vendidos por vendedor
df.groupby('Representante')['Qtde de Vendas'].sum().sort_values(ascending = False)

#Gráfico total de produtos vendidos por vendedor

# barh = Gráfico Horizontal
# bar = Gráfico Vertical
df.groupby('Representante')['Qtde de Vendas'].sum().sort_values(ascending = False).plot.barh(title = 'Total produtos vendidos')
plt.xlabel('Total')
plt.ylabel('Produto');

df.groupby(df['Vencimento'].dt.year)['Lucro'].sum().plot.bar(title = 'Lucro x Total')
plt.xlabel('Ano')
plt.ylabel('Receita');

df.head(40)

#Selecionando apenas as vendas de 2012
df_2012 = df[df['Vencimento'].dt.year == 2012]

df_2012.head(11)

#Gráfico de linhas por mês no ano de 2012
df_2012.groupby(df_2012['Vencimento'].dt.month)['Lucro'].sum().plot(title = 'Lucro x Mês')
plt.xlabel('Mês')
plt.ylabel('Lucro');

#Gráfico de barras por cidade no ano de 2012
df_2012.groupby('Estado')['Lucro'].sum().plot.bar(title = 'Lucro x Estado')
plt.xlabel('Estado')
plt.ylabel('Lucro')
plt.xticks(rotation = 'horizontal'); #Eixo x na Horizontal

#Análise Estatística

df['Vencimento'].describe()

#Salvar em csv ou xlsx
df.to_excel('df-vendas-novo.xlsx', index = False)